apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-server
  template:
    metadata:
      labels:
        app: file-server
    spec:
      containers:
        - name: file-server-container
          image: 192.168.0.2:5000/file_server_image:1.0.7
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: file-server-secret
                  key: APP_KEY
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: file-server-secret
                  key: USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: file-server-secret
                  key: PASSWORD
          volumeMounts:
            - mountPath: /server/storage
              name: file-server-pv-storage
      volumes:
        - name: file-server-pv-storage
          persistentVolumeClaim:
            claimName: file-server-pvc
