services:
  file_server:
    build:
      context: .
    image: file_server:local
    container_name: file_server
    environment:
      APP_KEY: ${APP_KEY}
      USERNAM: ${USERNAME}
      PASSWORD: ${PASSWORD}
    ports:
      - "30006:8000"
    volumes:
      - /persistent_volumes/file_server/storage:/server/storage:Z
    restart: unless-stopped
