apiVersion: v1
kind: Secret
metadata:
  name: file-server-secret
type: Opaque
data:
  APP_KEY: Z0dsTG5pcjRQVnJveGJlS3U2encxRnA0b1JHOURUaE9YNElRN3l6Umw5Znk4dlNCd0E=
  USERNAME: bWlrZWxl
  PASSWORD: fnJ1Y2t2ZXJzaWNoZXJ1bmc=
