apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-server-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/persistent_volumes/file_server/storage"
