apiVersion: v1
kind: Service
metadata:
  name: file-server-service
spec:
  selector:
    app: file-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30005
  type: NodePort