apiVersion: v1
kind: Service
metadata:
  name: http-server-service
spec:
  selector:
    app: http-server
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 8000
      nodePort: 30005
  type: NodePort

