apiVersion: v1
kind: PersistentVolume
metadata:
  name: http-server-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/persistent_volumes/http_server/storage"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: http-server-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
